FROM golang:1.15 AS builder

WORKDIR /go/src/github.com/eventually-rs/saving-goals-go

ADD go.mod go.mod
ADD go.sum go.sum
RUN go mod download

COPY . .

RUN make build-saving-goals-api

# ------------------------------------------------------------------------------

FROM alpine:3.13

COPY --from=builder \
    /go/src/github.com/eventually-rs/saving-goals-go/saving-goals-api \
    /bin/saving-goals-api

ENTRYPOINT ["saving-goals-api"]
