FROM golang:1.15 AS builder

WORKDIR /go/src/github.com/eventually-rs/saving-goals-go

ADD go.mod go.mod
ADD go.sum go.sum
RUN go mod download

COPY . .

RUN make build-saving-goals-consumers
RUN make build-saving-goals-cli

# ------------------------------------------------------------------------------

FROM alpine:3.13

COPY --from=builder \
    /go/src/github.com/eventually-rs/saving-goals-go/saving-goals-consumers \
    /bin/saving-goals-consumers

COPY --from=builder \
    /go/src/github.com/eventually-rs/saving-goals-go/saving-goals-cli \
    /bin/saving-goals-cli

ENTRYPOINT ["saving-goals-consumers"]
